### ISSUE TITLE
時間の管理について

### ISSUE THREAD

**Issue by nimiusrd** [YNUWAIWAI/werewolf-client#10]
- [x] 「１日目昼」の右に残り時間（分秒）として「残り4'29」を追加する．
- [x] カウントダウンをして，終わったら「終了」と赤字で表示する．
- [x]  各メッセージの最終行に時刻表示として、「2017/10/11 12:30'45（残り4'29）」を追加する
-> サーバーから文字列が送られてくるのでガワだけ作る #25
- [x] ~昼の会話フェーズは１０分、昼の投票３分、夜の人狼や狩人や占い師の選択３分をデフォルトにする~なし
- [x] 昼会話フェーズ１０分→昼投票フェーズ３分→夜特殊役職（人狼，占い師，狩人）のフェーズ３分→昼会話フェーズ・・・の流れで行う-> サーバーから送られてくるのを流し込むだけでいい

時間を管理する部分はmoment.jsあたりでも使うかも？

**Comment by ktr-skmt** [comment]
「2017/10/11 12:30'45（残り4'29）」はサーバから送られてくる時間を表示
サーバからStringで送ります

**Comment by nimiusrd** [comment]
# タイマーについて

## 前提
時間の計算をフェイズの始まる時間を`phaseStartTime`，フェイズの時間を`phaseTimeLimit`とする．

## 今まで
`phaseTimeLimit`から残り時間を計算し，そこから`window.setInterval`で1000ミリ秒ごとに残り時間を減らしていた．
この方法だと最初の通信の遅延が心配．`window.setInterval`が本当に1000ミリ秒ごとに実行されるか心配．

## 改善法？
`phaseStartTime`のUNIX時間に`phaseTimeLimit`を足して，現時刻のUNIX時間を引くことで残り時間を計算する．
毎秒`new Date()`するが恐らく大丈夫．

**Comment by nimiusrd** [comment]
HighResolutionTimeを使うのがよさそう
https://developer.mozilla.org/ja/docs/Web/API/Performance/now
https://www.w3.org/TR/hr-time-2/
https://triple-underscore.github.io/hr-time-ja.html
