### ISSUE TITLE
最終結果の表示

### ISSUE THREAD

**Issue by nimiusrd** [YNUWAIWAI/werewolf-client#20]
- [x] 誰（どの陣営）が勝ったか
- [x] 生死
- [x] 死因

死因は以下
- 処刑死：昼の投票によって殺害された場合
- 襲撃死：夜の人狼の襲撃によって殺害された場合
- 恐怖死：夜に占い師が占ったことによってハムスター人間が死に至った場合
- 変死：昼の会話に一切参加しなかったプレイヤは自動的に死に、変死として扱う

**Comment by ktr-skmt** [comment]
忘れていたけど、
アバターの画像と名前は、サーバがランダムに選択したものなので、最終結果表示の表に実際のユーザのアバター（画像と名前）も表示した方がいいかも

**Comment by nimiusrd** [comment]
|ゲーム内での名前|生死|勝ち負け|役職|実際の名前|
|:------:|:------:|:------:|:------:|:------:|
