### ISSUE TITLE
結果のキャプションについて

### ISSUE THREAD

**Issue by nimiusrd** [YNUWAIWAI/werewolf-client#205]
- 「人間チーム」，「人狼チーム」となっているが，人間と人狼とハムスター人間の3勢力がいるので，この表現は不適切
- 「チーム」という表現ではない方がいい（？）考えられる候補は以下．
  - 勢力
  - 陣営
  - 何もつけない

**Comment by ktr-skmt** [comment]
村人陣営，人狼陣営，ハムスター人間陣営
