### ISSUE TITLE
indexeddbの削除処理がうまくいってない

### ISSUE THREAD

**Issue by nimiusrd** [YNUWAIWAI/werewolf-client#294]
ようにみえるがクライアント側の実装は想定した通りの振る舞いをしていた．
leaveWaitingPageをサーバーに送った直後に（謎の）waitingPageが送られていることが原因．

**Comment by ktr-skmt** [comment]
サーバ側のleaveWaitingPageの処理がうまくいってなさそうですね。
確認してみます。
